### ISSUE TITLE
Allow making recent folders just those moved/copied to

### ISSUE THREAD

**Issue by anathusic** [kewisch/quickmove-extension#102]
Since last version I miss the search box in context menu.
Can you please add serach box again.

Other thing: 
The number of recent folders in the Quick Move dialog is incorrect.
I have defined 20 folders in the configuration dialog, but only 5 are displayed in the “Quick Move” dialog! I would like the most recently used folders to be displayed at the top, such as in the context menu. What I'm seeing at the moment isn't really helpful. There are many different folders divided into groups of my configured email accounts, but for me only the most recently used ungrouped folders are of interest (which are at the bottom of the dialog). I either use the recently used folders or the search function.

**Comment by kewisch** [comment]
Are the recently used folders in a different order than those in the context menu?

Unfortunately the context menu is not coming back, the new extensions technology does not support modifying the context menu so I cannot re-add that.

**Comment by anathusic** [comment]
It's a shame that the search box is no longer possible in the context menu.

Yes, the most recently used folder doesn't even exist there. Here is a photo of my "Quick Move" dialog:
![grafik](https://github.com/kewisch/quickmove-extension/assets/81009348/fb5a29ba-f0b5-4e97-9c7e-d6ed0935e8eb)
I can only see 3 recently used folders and they are randomly distributed across all email accounts.
I would prefer exactly one main folder "Recent Used Folders" in which all of them are listed like in the context menu.

**Comment by kewisch** [comment]
Inboxes and Sent folders also count as recently used folders, so you're getting closer to 15 there :) I think this was the same as before? I'm not sure this is in 2.0.1, but there should be an option to set how many recent folders to show. Also, in the upcoming 2.6.3, there will be a way to pick specific folders instead of showing recent ones.

Here is a preview of the upcoming version: [quick_folder_move-2.6.3.zip](https://github.com/kewisch/quickmove-extension/files/12778283/quick_folder_move-2.6.3.zip)

**Comment by costasvassilakis** [comment]
It's a shame that the search box cannot be used in the context menu. This deprives the plugin of its (probably) most useful functionality.

**Comment by kewisch** [comment]
Indeed, though I can understand that a such feature in the Thunderbird extensions API wouldn't be very future-proof. To me the main feature was always being able to open the popup via keyboard shortcuts, so you don't actually have to use the mouse much and can triage quickly. With the new version, the closest you have is the button in the message header, which is also in context for the action you are taking. It is also one click less then going through the context menu :)

I know it will take changing some muscle memory, but given what a hack the context menu was I think it is for the better.

**Comment by costasvassilakis** [comment]
Thanks kewisch. Using the "quick move" button in the message context (or even better a keyboard shortcut!) would be a way round the issue, for me however it does not seem to work since I'm not getting a search box when the button is pressed.
![image](https://github.com/kewisch/quickmove-extension/assets/29659878/4117abe1-87dd-4b89-9268-3226132466a0)
This also happens with the "quick move" button on the application window bar
![image](https://github.com/kewisch/quickmove-extension/assets/29659878/a9eb7d9a-5e30-4bb2-aec8-d7c74a7d809c)
(the search box appearing above the "move/copy/goto/tag" menu is Thunderbird's standard search widget).
The message header button is not optimal for all cases though, since it works at single message level, while many times multiple messages need to be moved to the same folder (e.g. a thread; results of a search or a quick filter; individually selected messages in the message list pane). If the keyboard shortcut or the button on the application window bar would cover these use cases, that would be fine!

**Comment by anathusic** [comment]
> Inboxes and Sent folders also count as recently used folders, so you're getting closer to 15 there :) I think this was the same as before? I'm not sure this is in 2.0.1, but there should be an option to set how many recent folders to show. Also, in the upcoming 2.6.3, there will be a way to pick specific folders instead of showing recent ones.
> 
> Here is a preview of the upcoming version: [quick_folder_move-2.6.3.zip](https://github.com/kewisch/quickmove-extension/files/12778283/quick_folder_move-2.6.3.zip)

I can confirm the problem of [costasvassilakis](https://github.com/costasvassilakis)
In version 2.6.3 there is no search box anymore.

**Comment by anathusic** [comment]
> Inboxes and Sent folders also count as recently used folders, so you're getting closer to 15 there :) I think this was the same as before? I'm not sure this is in 2.0.1, but there should be an option to set how many recent folders to show. 

Yes there is an option to set the count of visible last folders.
But it is not what I am searching for. Because I dont want to see the visited Inboxes, Sent-Folders or local folders.
For shure I have that folders in the context menu too but there I have a extra folder called "Recent" where that boxes are not shown! And it would be greate if I would see this "Recent" folder, I moved something, on top of the new Quick move diaolg.  

![grafik](https://github.com/kewisch/quickmove-extension/assets/81009348/15ad90ec-1c5a-4019-9738-139c793e4a0f)

I think I understand the problem now.
The most recently visited (clicked on) folders are displayed in the
"Quick move" dialog chronologically. It doesn't matter if I moved something there or not. But what I need is a view of just the folders I moved something to!

**Comment by kewisch** [comment]
That sounds accurate. Morphing this into a feature request where I would put a checkbox in the options that would allow users to switch between most recent by Thunderbird's MRUTime, vs most recent by recently used in QFM. Thanks for bearing with me on this!

**Comment by kewisch** [comment]
I'm going to fix this by allowing to switch between most recently modified and most recently accessed. Thunderbird saves these two modes in the background. The WebExtensions API isn't ready for this yet and I'm not sure it will provide that amount of diferentiation, but let's go with this for now.

[quick_folder_move-3.0.0pre.zip](https://github.com/user-attachments/files/18049988/quick_folder_move-3.0.0pre.zip)
