### ISSUE TITLE
Extension Shortcuts in TB115

### ISSUE THREAD

**Issue by l8com** [kewisch/quickmove-extension#108]
The default shortcuts (e.g. Ctrl-Shift-M) do not work in TB115 and should be replaced. It would be nice if two-key shortcuts were possible, too.

**Comment by kewisch** [comment]
Hey, please check out the new version in #88. There is a version I'd appreciate testing with.

**Comment by l8com** [comment]
Sorry I did not chech [#88 ](https://github.com/kewisch/quickmove-extension/issues/88) before opening this issue. In #88 I can find [sources for 2.6.3](https://github.com/kewisch/quickmove-extension/files/12778283/quick_folder_move-2.6.3.zip). Can you provide and xpi for testing?

**Comment by b3** [comment]
Hey @l8com, you can get access to the zip file link in [this comment](https://github.com/kewisch/quickmove-extension/issues/88#issuecomment-1742209822) of the #88 issue.

**Comment by l8com** [comment]
thanks, I have unpacked - but I don't know how to use it without an xpi. I would test it but don't bother if you think it's not worth it.

**Comment by b3** [comment]
You do not need to unzip it to test it:

1. To go the addons manager tab (menu *Tools > Addons and Themes*)
2. Click on the gear the top of the tab (right to the header *Managing your extensions*)
3. Click on the *Install addon from a file*
4. Select and choose the zip file.

Labels quoted here are approximation of what you may find on your Thunderbird since mine is running in french (I translated them).

**Comment by kewisch** [comment]
Indeed, as noted. An xpi file is basically a zip file, and since a while Firefox/Thunderbird allows installing them regardless of if they have an .xpi or .zip ending.
