### ISSUE TITLE
Selection highlight color difficult to distinguish from account background

### ISSUE THREAD

**Issue by mclaborn** [kewisch/quickmove-extension#116]
TB 115.3.1
QuickMove 2.6.9
Ubuntu 20.04

The color that highlights the selected/chosen folder in the move window is very similar to the background color of an account line, making it very difficult to distinguish them one from another .

See attached screen shot. 
![qm](https://github.com/kewisch/quickmove-extension/assets/1437059/c63500dd-a2bd-420c-a556-d5ce53bc3d70)

**Comment by kewisch** [comment]
Fixed in f47d3186a9b6dfa260fd6132b37fcd1744a9179f

<img width="178" alt="image" src="https://github.com/kewisch/quickmove-extension/assets/607198/a26b93b0-bc87-417d-940e-af1de59af98b">
<img width="199" alt="image" src="https://github.com/kewisch/quickmove-extension/assets/607198/ce0f21a8-e235-45fe-a0d4-3c0004d3ec48">

In dark mode the contrast to the icons is not great. I tried to use colors already in Thunderbird, but the hover color for the thread pane is pretty dark so I went with the lighter color.

**Comment by mclaborn** [comment]
Can you provide instructions for me to try out these two fixes?

**Comment by kewisch** [comment]
Sure! I just happened to provide instructions on how to do this in https://github.com/kewisch/quickmove-extension/issues/106 based on the repo, but here is also a current version from main (with version number bumped):

[quick_folder_move-2.8.0.zip](https://github.com/kewisch/quickmove-extension/files/12899118/quick_folder_move-2.8.0.zip)

**Comment by mclaborn** [comment]
This is great!
