### ISSUE TITLE
Input not recognised when typing too early.

### ISSUE THREAD

**Issue by tessarakt** [kewisch/quickmove-extension#13]
Version: 2.0.0pre1

Steps to reproduce:
1. Press Shift-G.
  => First, the Buttons "Move", "Copy" and "Goto" and a text box will appear.
2. Immediately type something.

Expected result: The typed string is entered into the text box.
Actual result: The typed string does not appear in the text box. Instead, it is apparently still processed by the folder list, and can trigger (via keyboard shortcuts) actions like watching a thread.

**Comment by bbceg** [comment]
Just for the record, this appears to be a problem with previous versions. I'm running 1.6.1 on Thunderbird 60.9.1 and if you press Shift+M and start typing before the search box/folder list appears, you can unwittingly apply all manner of properties to your emails (as you have described @tessarakt ). Is there a chance this is more of a Thunderbird issue rather than a plugin issue and if so is it worth raising this elsewhere?

**Comment by kewisch** [comment]
Probably a timing issue with the addon actually. For 2.x I might have to reduce the initialization time before the textbox is displayed and focused. If that is not enough I might be able to fix it in Thunderbird. For 1.x I could probably do more by stopping keypresses after the shift+[MGY] keys are used. This is a good tip though, I saw this much more in 2.x

**Comment by bbceg** [comment]
This is a little off topic but I've been using 2.0 consistently for about a week (although exclusively the move functionality) and with the exception of this issue, 2.0 is working well for me on Thunderbird 68.3.0 on Windows 10. Not sure if this counts as "testing" but thought I'd post in case it helped!

Also off topic, but why are there two pre-release versions (1.7 and 2.0)? Would it be more helpful to test with one instead of the other?

Let me know if queries / comments like this would be better posted elsewhere. I wasn't sure where else made sense.

**Comment by kewisch** [comment]
1.7 is built on the same codebase as 1.6 and 2.0 is a rewrite. I added 1.7 because there were still some bugs in Thunderbird that don't make me confident I could soon release it as a replacement. 

Based on feedback I got I'm likely going to release 1.7 soon, so if you like please do continue with 2.0.

**Comment by sbsrouteur** [comment]
Hi, 

I think I have the same issue, when I click the menu to use quickfolder to move messages the popup shows up. I start typing and the menu will randomly go away ignoring input which is there used to mess my mailboxes, since most lettres trigger an action.

Is there a workaround , as this is super annoying (even though extension is great)

**Comment by bbceg** [comment]
Not wildly helpful, but I recently upgrade my PC (10 year old i7 but with an upgraded SSD) to a recent core i5 + NVMe SSD and this issue has all but disappeared. I appreciate buying a new PC is _probably_ overkill for this issue alone...

**Comment by sbsrouteur** [comment]
If it may help, when logging my comment I found out that Shift+M would pop-up the menu as well and it does not seem to make the problem. It only appears when going through the context menu via right click on a message in the message list panel.

**Comment by kewisch** [comment]
I think what we have in v2 is all I can do here. If there is typing before the popup window complets opening, I don't think I can capture that input. You'll  have to train your muscle memory to pause for a few milliseconds before typing. If someone has a specific idea for improvement, a pull request is very welcome!
