### ISSUE TITLE
Update on this closed issue:  pop-up does not show - the issue is still there but I've narrowed it down a bit:

### ISSUE THREAD

**Issue by afmoene** [kewisch/quickmove-extension#146]
Update on this closed issue: the issue is still there but I've narrowed it down a bit:

The issue (popup not showing) only occurs when I have the Compact Headers extension enabled (https://addons.thunderbird.net/en-US/thunderbird/addon/compact-headers/)
More specifically: 
- when I have the headers collapsed, the pop-up does _not_ show
- when I have the headers not collapsed, the pop-up _does_ show

I have no programming experience with Thunderbird extensions, so I have no idea how the two would interact. Nor, which of the two extensions would be the cause of this unintended interaction. Hence, I do not know wha twould be the way forward. 

PS: I'm the same person as that opened the original issue (afmoene), I'm just inconsistent with the github account that I use for different tasks.

_Originally posted by @scientific-method-course in https://github.com/kewisch/quickmove-extension/issues/138#issuecomment-2016739754_

**Comment by ernstki** [comment]
Pretty sure you nailed it here. Thanks for the big hint.

I hide as many user interface elements as I possibly can, relying heavily on [Compact Headers](https://addons.thunderbird.net/en-US/thunderbird/addon/compact-headers/) since recent Thunderbird updates [took away](https://bugzilla.mozilla.org/show_bug.cgi?id=1556261) the ability to customize the message pane's toolbar.

Some observations:

* Seems like _both_ toolbar buttons need to be visible in order for all the shortcuts to work.
* The shortcut for "Goto" (<kbd>Shift</kbd>+<kbd>G</kbd> with "legacy" shortcuts) activates the application-level toolbar button. 
* The other three shortcuts activate the toolbar button in the message page.

![Animated GIF demonstrating the behavior of Shift+G shortcut, which opens the UI attached to the top application toolbar (to the right of the search bar), then the Shift+Y shortcut, which opens the UI attached to the message pane, next to the buttons for 'Forward,' 'Archive,' 'Junk,' and so on](https://github.com/user-attachments/assets/11ac7dcf-a4d1-4883-aa14-00c92886d1cf)

If both buttons are hidden, either through Thunderbird's built-in customization or the Compact Headers extension, there's no UI to show when you press the shortcuts, so the shortcut behavior just appears broken.

There probably isn't much that @kewisch can do to fix this, short of:

* architectural changes to Thunderbird
* radically modifying this extension's user interface, to be a popup window, for example, instead of a [door hanger](https://wiki.mozilla.org/Thunderbird:UX:Test_Pilot#Door_Hanger_Notification) that's affixed to the toolbar
* …or winding back the clock.

But at least I know that these two extensions are—for now—an either-or deal.

**Comment by scientific-method-course** [comment]
Many thanks for this clarification and a view behind the scenes (including all your links). 

Given that a simple solution is not around the corner, I will try to find out how work around this situation. As a programmer myself I recognized that one  can make certain design choices that turn out to be sub-optimal at a much later stage (but would required a large redesign to solve).

**Comment by kewisch** [comment]
I am certainly limited by what the Thunderbird WebExtensions API allows me to do. I don't want to go back to custom UX. My extension tries to use the message header bar first it that is visible, and if not then the main popup. 

Maybe there are ways for compact headers to keep the surface available for extensions?

**Comment by ernstki** [comment]
> I am certainly limited by what the Thunderbird WebExtensions API allows me to do. I don't want to go back to custom UX.

Thanks for chiming in, @kewisch. Agreed on all counts, _and_ not having had to contend with either API or UI design for Thuderbird extensions myself, obviously I respect your position. But solely as a user, part of me remains wistful about what the old XUL-based extensions were capable of, relative to the modern API.

> My extension tries to use the message header bar first it that is visible, and if not then the main popup.

Unless it's some weirdness particular to my installation, the latest Quick Folder Move (with _no_ other extensions active) uses the main popup for "Go To," but the message header bar for the others. Different behavior, even when both are visible, as seen in the GIF above.

**Comment by kewisch** [comment]
Ah yes indeed, I remember I intentionally went with the main toolbar first for goto. It makes sense though: going to a folder is not an action on the message, so it doesn't make sense to open the message header toolbar button. It will fall back to that one if the main toolbar isn't available.

**Comment by RealRaven2000** [comment]
> Ah yes indeed, I remember I intentionally went with the main toolbar first for goto. It makes sense though: going to a folder is not an action on the message, so it doesn't make sense to open the message header toolbar button. It will fall back to that one if the main toolbar isn't available.

Another reason for avoiding this is that (at least in classic folder views, where the header bar is in the center) this actually limits the length of the search dropdown, so it is actually better to locate it up top.

**Comment by kewisch** [comment]
@afmoene Is there anything specific I can do on this issue? I'm not 100% sure what the problem is, and if it is any different from #158

**Comment by afmoene** [comment]
@kewisch, I just discovered/realised that the Compact Headers extension has a setting 'Single line headers' that you can toggle. When I switched that off, the header became a compact 2-line header which _does_ reveal the Quick Move button! For me this is a very nice compromise: the header is still sufficiently compact *and* I can use the short-cut for the Quick Folder Move.

You're clear technical analysis above helped a lot!

**Comment by kewisch** [comment]
Thank you so much! I'm glad you found a compromise, let's hope #158 will fix the rest.
