### ISSUE TITLE
Cannot add archive sub-folders to default folders

### ISSUE THREAD

**Issue by RasmusMalver** [kewisch/quickmove-extension#154]
Hi! I love the plugin, but have an issue: My archive folder has sub-folders, based on the overall topic of an email. When setting `default folders`, those folders do not appear in the search. I've tried using full path, to no avail.

Is this on purpose?

<img alt="A screenshot showing the issue" src="https://github.com/kewisch/quickmove-extension/assets/1069447/55be130a-f615-4bd0-a5b4-ed59e3c6980d" width="564">

<img alt="A screenshot showing the issue, using full path" src="https://github.com/kewisch/quickmove-extension/assets/1069447/003bdf32-e740-4a1e-a19e-2eda92769300" width="564">

**Comment by kewisch** [comment]
No, this is not intentional. I would have expected it to work, but there is definitely a bug of sorts in the code here:

https://github.com/kewisch/quickmove-extension/blob/e5490f3ae4bb806c1cd016335b1e35743c2a97b6/src/options/options.js#L75

I don't see skipArchive defined anywhere, but it should be undefined which is falsy. We'll need to investigate what value this needs to get, and potentially update the folder node tree if the never match archive folders option is switched.

**Comment by kewisch** [comment]
[quick_folder_move-2.9.3pre.zip](https://github.com/user-attachments/files/17853265/quick_folder_move-2.9.3pre.zip)

Could you give this a test drive?

**Comment by kewisch** [comment]
I'm going to consider this fixed with the changes I made, please open a new issue if it doesn't work in the next release version. Thanks for filing this issue!
