### ISSUE TITLE
Thunderbird 128 (Nebula) Update and Quick Move Not Seeing Office 365/Owl folders?

### ISSUE THREAD

**Issue by SaintDoormatius-cmyk** [kewisch/quickmove-extension#160]
Since updating to Nebula (128) and the newly updated add-on for Quick Move (thank you for getting that out so quickly!), I have noticed that Quick Move no longer finds/shows the folders in my Office 365 account through Owl.  Previously, this was no problem on Supernova with this add-on, but now it is only showing my Gmail account and Personal account via my personal web domain.  Is this a known issue, or am I doing something wrong?  I do have "All Folders" checked in the settings for the add-on.

**Comment by DrCheese-mac** [comment]
I have noticed the same problem with TB128.0.1esr (64-bit) and Owl for Exchange v.1.3.2. Works fine in TB115.

**Comment by kewisch** [comment]
Can you try again with quick folder move 2.9.2 ? It is possible that this might not work due to the folder/account types. Another reason might be https://bugzilla.mozilla.org/show_bug.cgi?id=1909005 which has just been fixed. Unfortunately I can't easily work around this so you'll have to wait until that version of Thunderbird is available

**Comment by SaintDoormatius-cmyk** [comment]
Thanks @kewisch !  Just to confirm, I updated to 2.9.2 and it's still not showing the Owl/Exchange folders in the Quick Move toolbar.  Must be that bug that got fixed and will (presumably) be in v 131?  If so, I can just wait for that to hit the main release channel. I appreciate the help!

**Comment by kewisch** [comment]
Yes, that should be the best course of action. It might be uplifted to a 128 point release as well.
