### ISSUE TITLE
"Recent folders" option includes folders affected by filters

### ISSUE THREAD

**Issue by rpedrica** [kewisch/quickmove-extension#176]
The "Recent folders" default folders option results in folders used in Thunderbird filters being included. E.g. If I have a filter which moves email X with values Y from Inbox A to folder B, then both Inbox A and folder B are included in the recent folders list. This is understandable as QuickMove is probably just looking at folders accessed irrespective of whether that was done auto through some background function or manually by the user. News feeds folders are also affected here.

Is it possible to make a variation of "Recent folders" where only folders selected interactively by users are included in the list, thereby ignoring folders affected by background/automatic actions. So in the same way as Thunderbird's Move to -> Recent list works?

I know that the "Specific folders" option is available however that requires manual intervention and removes the automated and dynamic filling out of the list.

**Comment by kewisch** [comment]
This should rather be fixed in Thunderbird itself, so that background operations don't affect the recent time of the folder. I'm not sure that is easily possible since it uses a general "MTUTime" field. In theory we should be getting the same list of folders that Thunderbird's move to list provides, are you saying they differ?

**Comment by rpedrica** [comment]
Hi @kewisch, yes there is a difference between what TB shows in its Recent list compared to QuickMove. TB only stores entries in its Recent list that have been selected manually by the user in a move/copy operation (although you don't have to manually preset these folders, which gives a semi-manual/dynamic operation).

Whereas QuickMove is including folders where an auto/background operation has occurred, and across ALL fodlers. So to my suggestion to offer an option in QuickMove that mirrors the TB method.

But it sounds like you're basing the Recent Folders option on a time value in TB across ALL folders. Would it be possible to restrict this (or offer an option) to any folder not INBOX or affected by message filters?

Regards, Robby

**Comment by kewisch** [comment]
Can you try this version? With Thunderbird 128 I was aiminig to use the built-in recent folders extension API, which uses MRUTime (most recently used). I see the folder popup uses MRMTime (most recently modified). I've reverted back to using a custom API and switched to MRMTime.

This version will unfortunately not include folders that you've selected manually, which I think also has value. It might also include folders that have been changed due to a background operation, which would also be the case with the original context menu.

I'm not sure how to solve this issue without sticking to legacy APIs or yet another change to Thunderbird with an already somewhat flaky API, but here is a start to figuring it out.

[quick_folder_move-2.9.3pre.zip](https://github.com/user-attachments/files/17533137/quick_folder_move-2.9.3pre.zip)

**Comment by rpedrica** [comment]
Hi Philipp

1. apologies for the delay in reply but I had some eye surgery recently that meant I couldn't compute for a few days
2. I've installed this ver and on the face of it, it's doing exactly what I wanted it to do
3. give me a few days to use this ver and I'll give you more feedback

Regards, Robby

**Comment by kewisch** [comment]
I chatted with someone working on Thunderbird here. The mismatch in API and Thunderbird behavior is not intentional.

There is some debate which approach is correct (most recently used vs most recently modified). 

I can probably go back to a custom api in the meanwhile. The filters aside, some users might prefer seeing folders they have selected (most recently used), instead of only folders they have moved messages to (most recently modified).

Letting quickmove users decide in the preferences seems sensible, but also adds more complexity.

Unfortunately I can't simply exclude automated actions since there is no folder time value for that.

**Comment by kewisch** [comment]
I'm resolving this by adding a way to switch between most recently modified and most recently added folders. I believe Thunderbird itself will go to most recently accessed for everything. I don't know how long I'll keep this since it relies on legacy APIs I'd like to get rid of, in the worst case I could add a mode where it remembers its own list of recent folders and only shows those where you've moved via this add-on.

[quick_folder_move-3.0.0pre.zip](https://github.com/user-attachments/files/18050004/quick_folder_move-3.0.0pre.zip)
