### ISSUE TITLE
Feature request : search not sensible to accented characters

### ISSUE THREAD

**Issue by CharlesDelorme** [kewisch/quickmove-extension#193]
Today search is not sensible to case. That's great. Could it be possible not to be sensible so accented characters ? 

I may sometime use french or english word while naming folders. For example "vidéo" in french or "video" in english. 

So I need to search both words to find the right folder (or stop at "vid" and see the results)

There is no real rules for that naming and I might as well rename the folders of course :-)

But if there is an already simple solution for that, it would be great

**Comment by kewisch** [comment]
How is this?

[quick_folder_move-3.0.1.zip](https://github.com/user-attachments/files/18247364/quick_folder_move-3.0.1.zip)

**Comment by kewisch** [comment]
This solution will ignore accents if you don't have an accent in your search string, but match for them if you do. So if you type "vide" it will match "vidéo" and "videorecorder", but if you type "vidé" it will only match "vidéo". This seemed most sensible because if someone types an accent they might really want to see an exact result.

**Comment by CharlesDelorme** [comment]
Yes, nice solution and works as expected. Thanks a lot !

**Comment by kewisch** [comment]
Will include this in the next release, thanks for the suggestion!
