### ISSUE TITLE
does not work with softmaker textmaker pro 2018 and thunderbird

### ISSUE THREAD

**Issue by jefken153** [kewisch/quickmove-extension#27]
I have thunderbird 68

**Comment by kewisch** [comment]
Unfortunately I don't have enough information to act on this report. What does not work? What Thunderbird version are you using? Do you get any error console messages? I likely have a few more questions, but let's start with these. I'm closing this bug since March is a while back and you might have resolved this in the meantime, but feel free to comment and we can reopen.
