### ISSUE TITLE
Create an option to show full path of folder

### ISSUE THREAD

**Issue by sangallidavide** [kewisch/quickmove-extension#31]
This is also one of the comments in the review and related to #25 #14 #2 

At present the default behavior is just to show the "folder name" under the "Move To" option when seraching. It adds the account if there are two accounts with the same "folder name" and the pat if there are two identical "folder name" within the same account, but under different folders.

I'd really like, for example, to always see the full path with the account nearby.
Maybe some others would not like it.
It would be great to be able to decide the behavior.

**Comment by RealRaven2000** [comment]
If you like @kewisch check out the way the folder display is handled by the quickMove function in my Add-on [QuickFolders](https://github.com/RealRaven2000/quickfolders). You can configure what is shown, (how many levels you want to go up) but I think the default is showing the parent folder at least:

![image](https://user-images.githubusercontent.com/6314674/81329100-f0a39280-9095-11ea-9ee7-8403558c2c34.png)

(In the example above I also add the name of the parent folder in order to narrow down results, as I have more than 270 folders) You can configure what you see exactly here:

![image](https://user-images.githubusercontent.com/6314674/81329248-2d6f8980-9096-11ea-80e9-3ba6dfe8f2ef.png)

**Comment by ThomGr** [comment]
I support this request, an (optional) display of the full path would be really handy and make the urge for a Nostalgy update to TB78 go away almost completely...

**Comment by AlfonnsM** [comment]
I also sorely miss this functionality.  With very extensive folder structures, the folder name alone is not enough to find the desired destination. Thank you for the great job.

**Comment by kewisch** [comment]
There is n option for this by now.
